name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  MODULES: "../../generic/forth/core.forth ../../generic/forth/punit.forth ../../generic/forth/ringbuf.forth  ../../generic/forth/ringbuf_test.forth ../../generic/forth/test.forth"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: "cd arch/x86; gcc -m32 -nostdlib -I. ../../main.S -o punyforth"
    - name: chmod
      run: chmod +x arch/x86/punyforth
    - name: run stuff
      run: cat $MODULES | ./arch/x86/punyforth
